### ISSUE TITLE
requestStream.abort() unsafely called

### ISSUE THREAD

**Issue by walshie4** [stephenplusplus/retry-request#10]
Was using a google-cloud package that leverages common-grpc (https://github.com/GoogleCloudPlatform/google-cloud-node/tree/master/packages/common-grpc) and came across this error.

```
TypeError: requestStream.abort is not a function
```

The stack referenced the following line - https://github.com/stephenplusplus/retry-request/blob/master/index.js#L73

**Comment by stephenplusplus** [comment]
Thanks for reporting that. Could you let me know what method you called in which google-cloud package? That could be another issue.

I released a fix for this issue in v2.0.2.

**Comment by walshie4** [comment]
Happened when using `@google-cloud/bigtable` (v0.9.0) calling the `createReadStream` function with some illformed `start` and `end` keys.
