### ISSUE TITLE
Does it makes sense to retry on 4xx errors?

### ISSUE THREAD

**Issue by ofrobots** [stephenplusplus/retry-request#12]
Currently the default`shouldRetryFn` has behaviour `Default: Returns true if http.incomingMessage.statusCode is < 200 or >= 400`.

Does it make sense to retry on a `404` for example, or other client side errors? Doesn't that just delay the inevitable error callback?

I know I can override the behaviour by passing in my own `shouldRetryFn`, but what is the rationale for the default behaviour?

**Comment by stephenplusplus** [comment]
[General Google API advice](https://developers.google.com/drive/v3/web/handle-errors)
> Conversely, it is not a relevant strategy for dealing with errors unrelated to rate-limiting, network volume or response times, such as invalid authorization credentials or file not found errors.

For default behavior, maybe we should just special case 429, and not auto-retry on the other 4xxs? Let me know if you see other applicable ones: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_errors

**Comment by ofrobots** [comment]
SGTM on your proposal!

**Comment by stephenplusplus** [comment]
PR sent: #13
