### ISSUE TITLE
Request to add debug information

### ISSUE THREAD

**Issue by yihaozhadan** [stephenplusplus/retry-request#24]
Is it a good idea to add [debug](https://www.npmjs.com/package/debug) to the code? So that it helps to troubleshoot the retry issue.

For example, I would like to know *currentRetryAttempt*, the *elapsed time* between each retry and the *HTTP response status* in each retry, so that I know *retry-request* itself is working properly and I can get some statistics.

**Comment by stephenplusplus** [comment]
I do like that idea! Would you be interested in getting a PR started?

**Comment by yihaozhadan** [comment]
Sure. I can add the feature and create PR.

**Comment by stephenplusplus** [comment]
Fixed in #25. Thanks again!
