### ISSUE TITLE
Missing dependency on debug makes module unusable with pnpm

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [stephenplusplus/retry-request#27]
`pnpm` pushes hard to not let you rely on transitive dependencies.

This module has a hard dependency on `debug`, which it does not declare at all.

This is causing it to fail for me, and by extension making `google-gax` unusable for me.

**Comment by stephenplusplus** [comment]
:( Sorry. Just published 4.1.1 including `debug`.

**Comment by mgabeler-lee-6rs** [comment]
Confirmed fixed, thank you for the super-fast response :grinning: :heart:
