### ISSUE TITLE
Can we make the `response` event for streaming requests optional?

### ISSUE THREAD

**Issue by callmehiphop** [stephenplusplus/retry-request#7]
Relates to https://github.com/GoogleCloudPlatform/gcloud-node/issues/1443

I'm using grpc as a transport and it does not emit any kind of event to let me know if the initial request was successful or not, instead it waits until all data has been received. If I use retry-request in combination of grpc, then I run into an error where either all the data buffers in memory or the stream reaches capacity and can no longer be written to.

**Comment by stephenplusplus** [comment]
@callmehiphop going to close, I don't think there's anything to do here-- I might forget exactly what we're asking for,

**Comment by callmehiphop** [comment]
Yeah, I think we just changed the way we used gRPC.
